# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barstock.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BarStock(object):
    def setupUi(self, BarStock):
        BarStock.setObjectName("BarStock")
        BarStock.resize(800, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(BarStock)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barstock = QtWidgets.QTabWidget(BarStock)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.barstock.setFont(font)
        self.barstock.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.barstock.setIconSize(QtCore.QSize(16, 16))
        self.barstock.setElideMode(QtCore.Qt.ElideNone)
        self.barstock.setMovable(False)
        self.barstock.setTabBarAutoHide(False)
        self.barstock.setObjectName("barstock")
        self.spirits_tab = QtWidgets.QWidget()
        self.spirits_tab.setObjectName("spirits_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.spirits_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.spirits_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 1340))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setMinimumSize(QtCore.QSize(125, 160))
        self.label_21.setMaximumSize(QtCore.QSize(125, 160))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setMinimumSize(QtCore.QSize(125, 160))
        self.label_22.setMaximumSize(QtCore.QSize(125, 160))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setMinimumSize(QtCore.QSize(125, 160))
        self.label_24.setMaximumSize(QtCore.QSize(125, 160))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setMinimumSize(QtCore.QSize(125, 160))
        self.label_26.setMaximumSize(QtCore.QSize(125, 160))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 9, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setMinimumSize(QtCore.QSize(125, 160))
        self.label_25.setMaximumSize(QtCore.QSize(125, 160))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 8, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setMinimumSize(QtCore.QSize(125, 160))
        self.label_27.setMaximumSize(QtCore.QSize(125, 160))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 9, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setMinimumSize(QtCore.QSize(125, 160))
        self.label_28.setMaximumSize(QtCore.QSize(125, 160))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 9, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setMinimumSize(QtCore.QSize(125, 160))
        self.label_23.setMaximumSize(QtCore.QSize(125, 160))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setMinimumSize(QtCore.QSize(125, 160))
        self.label_10.setMaximumSize(QtCore.QSize(125, 160))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(125, 160))
        self.label_5.setMaximumSize(QtCore.QSize(125, 160))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMinimumSize(QtCore.QSize(125, 160))
        self.label_12.setMaximumSize(QtCore.QSize(125, 160))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(125, 160))
        self.label.setMaximumSize(QtCore.QSize(125, 160))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(125, 160))
        self.label_9.setMaximumSize(QtCore.QSize(125, 160))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setMinimumSize(QtCore.QSize(125, 160))
        self.label_15.setMaximumSize(QtCore.QSize(125, 160))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(125, 160))
        self.label_13.setMaximumSize(QtCore.QSize(125, 160))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setMinimumSize(QtCore.QSize(125, 160))
        self.label_8.setMaximumSize(QtCore.QSize(125, 160))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(125, 160))
        self.label_3.setMaximumSize(QtCore.QSize(125, 160))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setMinimumSize(QtCore.QSize(125, 160))
        self.label_7.setMaximumSize(QtCore.QSize(125, 160))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMinimumSize(QtCore.QSize(125, 160))
        self.label_4.setMaximumSize(QtCore.QSize(125, 160))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setMinimumSize(QtCore.QSize(125, 160))
        self.label_17.setMaximumSize(QtCore.QSize(125, 160))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setMinimumSize(QtCore.QSize(125, 160))
        self.label_20.setMaximumSize(QtCore.QSize(125, 160))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setMinimumSize(QtCore.QSize(125, 160))
        self.label_14.setMaximumSize(QtCore.QSize(125, 160))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMinimumSize(QtCore.QSize(125, 160))
        self.label_6.setMaximumSize(QtCore.QSize(125, 160))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(125, 160))
        self.label_2.setMaximumSize(QtCore.QSize(125, 160))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setMinimumSize(QtCore.QSize(125, 160))
        self.label_16.setMaximumSize(QtCore.QSize(125, 160))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setMinimumSize(QtCore.QSize(125, 160))
        self.label_19.setMaximumSize(QtCore.QSize(125, 160))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setMinimumSize(QtCore.QSize(125, 160))
        self.label_18.setMaximumSize(QtCore.QSize(125, 160))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setMinimumSize(QtCore.QSize(125, 160))
        self.label_11.setMaximumSize(QtCore.QSize(125, 160))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setMinimumSize(QtCore.QSize(125, 160))
        self.label_29.setMaximumSize(QtCore.QSize(125, 160))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 10, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setMinimumSize(QtCore.QSize(125, 160))
        self.label_30.setMaximumSize(QtCore.QSize(125, 160))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 10, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.barstock.addTab(self.spirits_tab, "")
        self.liqueur_tab = QtWidgets.QWidget()
        self.liqueur_tab.setObjectName("liqueur_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.liqueur_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.liqueur_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollArea_2.setFont(font)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 739, 1008))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_31.setMinimumSize(QtCore.QSize(125, 160))
        self.label_31.setMaximumSize(QtCore.QSize(125, 160))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 8, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setMinimumSize(QtCore.QSize(125, 160))
        self.label_33.setMaximumSize(QtCore.QSize(125, 160))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 8, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_35.setMinimumSize(QtCore.QSize(125, 160))
        self.label_35.setMaximumSize(QtCore.QSize(125, 160))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 8, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_38.setMinimumSize(QtCore.QSize(125, 160))
        self.label_38.setMaximumSize(QtCore.QSize(125, 160))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 8, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_39.setMinimumSize(QtCore.QSize(125, 160))
        self.label_39.setMaximumSize(QtCore.QSize(125, 160))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_41.setMinimumSize(QtCore.QSize(125, 160))
        self.label_41.setMaximumSize(QtCore.QSize(125, 160))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_42.setMinimumSize(QtCore.QSize(125, 160))
        self.label_42.setMaximumSize(QtCore.QSize(125, 160))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 5, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_43.setMinimumSize(QtCore.QSize(125, 160))
        self.label_43.setMaximumSize(QtCore.QSize(125, 160))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 6, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_40.setMinimumSize(QtCore.QSize(125, 160))
        self.label_40.setMaximumSize(QtCore.QSize(125, 160))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 2, 3, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_44.setMinimumSize(QtCore.QSize(125, 160))
        self.label_44.setMaximumSize(QtCore.QSize(125, 160))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 2, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_54.setMinimumSize(QtCore.QSize(125, 160))
        self.label_54.setMaximumSize(QtCore.QSize(125, 160))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 3, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_48.setMinimumSize(QtCore.QSize(125, 160))
        self.label_48.setMaximumSize(QtCore.QSize(125, 160))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 6, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_47.setMinimumSize(QtCore.QSize(125, 160))
        self.label_47.setMaximumSize(QtCore.QSize(125, 160))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 5, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_55.setMinimumSize(QtCore.QSize(125, 160))
        self.label_55.setMaximumSize(QtCore.QSize(125, 160))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 7, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_51.setMinimumSize(QtCore.QSize(125, 160))
        self.label_51.setMaximumSize(QtCore.QSize(125, 160))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 7, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_49.setMinimumSize(QtCore.QSize(125, 160))
        self.label_49.setMaximumSize(QtCore.QSize(125, 160))
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 6, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_46.setMinimumSize(QtCore.QSize(125, 160))
        self.label_46.setMaximumSize(QtCore.QSize(125, 160))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 6, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_57.setMinimumSize(QtCore.QSize(125, 160))
        self.label_57.setMaximumSize(QtCore.QSize(125, 160))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 3, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_56.setMinimumSize(QtCore.QSize(125, 160))
        self.label_56.setMaximumSize(QtCore.QSize(125, 160))
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 7, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_53.setMinimumSize(QtCore.QSize(125, 160))
        self.label_53.setMaximumSize(QtCore.QSize(125, 160))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 5, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_52.setMinimumSize(QtCore.QSize(125, 160))
        self.label_52.setMaximumSize(QtCore.QSize(125, 160))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 5, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_58.setMinimumSize(QtCore.QSize(125, 160))
        self.label_58.setMaximumSize(QtCore.QSize(125, 160))
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 7, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_45.setMinimumSize(QtCore.QSize(125, 160))
        self.label_45.setMaximumSize(QtCore.QSize(125, 160))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 2, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_50.setMinimumSize(QtCore.QSize(125, 160))
        self.label_50.setMaximumSize(QtCore.QSize(125, 160))
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 3, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.barstock.addTab(self.liqueur_tab, "")
        self.mixers_tab = QtWidgets.QWidget()
        self.mixers_tab.setObjectName("mixers_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mixers_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.mixers_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollArea_3.setFont(font)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -936, 739, 1340))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_61.setMinimumSize(QtCore.QSize(125, 160))
        self.label_61.setMaximumSize(QtCore.QSize(125, 160))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 8, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_62.setMinimumSize(QtCore.QSize(125, 160))
        self.label_62.setMaximumSize(QtCore.QSize(125, 160))
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 9, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_63.setMinimumSize(QtCore.QSize(125, 160))
        self.label_63.setMaximumSize(QtCore.QSize(125, 160))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 8, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_64.setMinimumSize(QtCore.QSize(125, 160))
        self.label_64.setMaximumSize(QtCore.QSize(125, 160))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 9, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_65.setMinimumSize(QtCore.QSize(125, 160))
        self.label_65.setMaximumSize(QtCore.QSize(125, 160))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 8, 3, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_66.setMinimumSize(QtCore.QSize(125, 160))
        self.label_66.setMaximumSize(QtCore.QSize(125, 160))
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 9, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_67.setMinimumSize(QtCore.QSize(125, 160))
        self.label_67.setMaximumSize(QtCore.QSize(125, 160))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 9, 3, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_68.setMinimumSize(QtCore.QSize(125, 160))
        self.label_68.setMaximumSize(QtCore.QSize(125, 160))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 8, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_69.setMinimumSize(QtCore.QSize(125, 160))
        self.label_69.setMaximumSize(QtCore.QSize(125, 160))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 3, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_70.setMinimumSize(QtCore.QSize(125, 160))
        self.label_70.setMaximumSize(QtCore.QSize(125, 160))
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 2, 3, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_71.setMinimumSize(QtCore.QSize(125, 160))
        self.label_71.setMaximumSize(QtCore.QSize(125, 160))
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 2, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_72.setMinimumSize(QtCore.QSize(125, 160))
        self.label_72.setMaximumSize(QtCore.QSize(125, 160))
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 5, 2, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_73.setMinimumSize(QtCore.QSize(125, 160))
        self.label_73.setMaximumSize(QtCore.QSize(125, 160))
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 6, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_74.setMinimumSize(QtCore.QSize(125, 160))
        self.label_74.setMaximumSize(QtCore.QSize(125, 160))
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 2, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_75.setMinimumSize(QtCore.QSize(125, 160))
        self.label_75.setMaximumSize(QtCore.QSize(125, 160))
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 2, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_76.setMinimumSize(QtCore.QSize(125, 160))
        self.label_76.setMaximumSize(QtCore.QSize(125, 160))
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 6, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_77.setMinimumSize(QtCore.QSize(125, 160))
        self.label_77.setMaximumSize(QtCore.QSize(125, 160))
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_3.addWidget(self.label_77, 5, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_78.setMinimumSize(QtCore.QSize(125, 160))
        self.label_78.setMaximumSize(QtCore.QSize(125, 160))
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 6, 2, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_79.setMinimumSize(QtCore.QSize(125, 160))
        self.label_79.setMaximumSize(QtCore.QSize(125, 160))
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_3.addWidget(self.label_79, 6, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_80.setMinimumSize(QtCore.QSize(125, 160))
        self.label_80.setMaximumSize(QtCore.QSize(125, 160))
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_3.addWidget(self.label_80, 3, 2, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_81.setMinimumSize(QtCore.QSize(125, 160))
        self.label_81.setMaximumSize(QtCore.QSize(125, 160))
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_3.addWidget(self.label_81, 7, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_82.setMinimumSize(QtCore.QSize(125, 160))
        self.label_82.setMaximumSize(QtCore.QSize(125, 160))
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 5, 3, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_83.setMinimumSize(QtCore.QSize(125, 160))
        self.label_83.setMaximumSize(QtCore.QSize(125, 160))
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 5, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_84.setMinimumSize(QtCore.QSize(125, 160))
        self.label_84.setMaximumSize(QtCore.QSize(125, 160))
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_3.addWidget(self.label_84, 3, 3, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_85.setMinimumSize(QtCore.QSize(125, 160))
        self.label_85.setMaximumSize(QtCore.QSize(125, 160))
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.gridLayout_3.addWidget(self.label_85, 7, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_86.setMinimumSize(QtCore.QSize(125, 160))
        self.label_86.setMaximumSize(QtCore.QSize(125, 160))
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.gridLayout_3.addWidget(self.label_86, 7, 2, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_87.setMinimumSize(QtCore.QSize(125, 160))
        self.label_87.setMaximumSize(QtCore.QSize(125, 160))
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.gridLayout_3.addWidget(self.label_87, 3, 1, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_88.setMinimumSize(QtCore.QSize(125, 160))
        self.label_88.setMaximumSize(QtCore.QSize(125, 160))
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.gridLayout_3.addWidget(self.label_88, 7, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_89.setMinimumSize(QtCore.QSize(125, 160))
        self.label_89.setMaximumSize(QtCore.QSize(125, 160))
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.gridLayout_3.addWidget(self.label_89, 10, 0, 1, 1)
        self.label_90 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_90.setMinimumSize(QtCore.QSize(125, 160))
        self.label_90.setMaximumSize(QtCore.QSize(125, 160))
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.gridLayout_3.addWidget(self.label_90, 10, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.barstock.addTab(self.mixers_tab, "")
        self.verticalLayout.addWidget(self.barstock)

        self.retranslateUi(BarStock)
        self.barstock.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BarStock)

    def retranslateUi(self, BarStock):
        _translate = QtCore.QCoreApplication.translate
        BarStock.setWindowTitle(_translate("BarStock", "Form"))
        self.label_21.setText(_translate("BarStock", "Sherry"))
        self.label_22.setText(_translate("BarStock", "Vermouth, Sweet"))
        self.label_24.setText(_translate("BarStock", "Tequila"))
        self.label_26.setText(_translate("BarStock", "Vodka"))
        self.label_25.setText(_translate("BarStock", "Vermouth, Dry"))
        self.label_27.setText(_translate("BarStock", "Vodka, Citrus"))
        self.label_28.setText(_translate("BarStock", "Whiskey, Canadian"))
        self.label_23.setText(_translate("BarStock", "Southern Comfort"))
        self.label_10.setText(_translate("BarStock", "Brandy"))
        self.label_5.setText(_translate("BarStock", "Bourbon"))
        self.label_12.setText(_translate("BarStock", "Angostura"))
        self.label.setText(_translate("BarStock", "Goldschlager"))
        self.label_9.setText(_translate("BarStock", "Rum, Gold"))
        self.label_15.setText(_translate("BarStock", "Beer"))
        self.label_13.setText(_translate("BarStock", "Beer, Stout"))
        self.label_8.setText(_translate("BarStock", "Rum, White"))
        self.label_3.setText(_translate("BarStock", "Champagne"))
        self.label_7.setText(_translate("BarStock", "Rum, Overproof"))
        self.label_4.setText(_translate("BarStock", "Rum, Dark"))
        self.label_17.setText(_translate("BarStock", "Cachaça"))
        self.label_20.setText(_translate("BarStock", "Schnapps, Peppermint"))
        self.label_14.setText(_translate("BarStock", "Rum, Coconut"))
        self.label_6.setText(_translate("BarStock", "Gin"))
        self.label_2.setText(_translate("BarStock", "Campari"))
        self.label_16.setText(_translate("BarStock", "Schnapps, Butterscotch"))
        self.label_19.setText(_translate("BarStock", "Schnapps, Peach"))
        self.label_18.setText(_translate("BarStock", "Brandy, Cherry"))
        self.label_11.setText(_translate("BarStock", "Schnapps, Apple"))
        self.label_29.setText(_translate("BarStock", "Whiskey, Irish"))
        self.label_30.setText(_translate("BarStock", "Whiskey, Scotch"))
        self.barstock.setTabText(self.barstock.indexOf(self.spirits_tab), _translate("BarStock", "             Spirits             "))
        self.label_31.setText(_translate("BarStock", "Sambuca"))
        self.label_33.setText(_translate("BarStock", "Strawberry Liqueur"))
        self.label_35.setText(_translate("BarStock", "Triple Sec"))
        self.label_38.setText(_translate("BarStock", "Sloe Gin"))
        self.label_39.setText(_translate("BarStock", "Chartreuse"))
        self.label_41.setText(_translate("BarStock", "Amaretto"))
        self.label_42.setText(_translate("BarStock", "Curacao, Blue"))
        self.label_43.setText(_translate("BarStock", "Grand Marnier"))
        self.label_40.setText(_translate("BarStock", "Blackcurrant Liqueur"))
        self.label_44.setText(_translate("BarStock", "Banana Liqueur"))
        self.label_54.setText(_translate("BarStock", "Cointreau"))
        self.label_48.setText(_translate("BarStock", "Hazelnut Liqueur"))
        self.label_47.setText(_translate("BarStock", "Creme de Cacao, Dark"))
        self.label_55.setText(_translate("BarStock", "Jägermeister"))
        self.label_51.setText(_translate("BarStock", "Mint Liqueur"))
        self.label_49.setText(_translate("BarStock", "Galliano"))
        self.label_46.setText(_translate("BarStock", "Irish Cream"))
        self.label_57.setText(_translate("BarStock", "Coconut Liqueur"))
        self.label_56.setText(_translate("BarStock", "Midori"))
        self.label_53.setText(_translate("BarStock", "Creme de Cacao, White"))
        self.label_52.setText(_translate("BarStock", "Curacao, Orange"))
        self.label_58.setText(_translate("BarStock", "Irish Mist"))
        self.label_45.setText(_translate("BarStock", "Black Raspberry"))
        self.label_50.setText(_translate("BarStock", "Coffee Liqueur"))
        self.barstock.setTabText(self.barstock.indexOf(self.liqueur_tab), _translate("BarStock", "            Liqueur            "))
        self.label_61.setText(_translate("BarStock", "Juice, Tomato"))
        self.label_62.setText(_translate("BarStock", "Simple Syrup"))
        self.label_63.setText(_translate("BarStock", "Mint Leaves"))
        self.label_64.setText(_translate("BarStock", "Sprite"))
        self.label_65.setText(_translate("BarStock", "Orgeat Syrup"))
        self.label_66.setText(_translate("BarStock", "Strawberries"))
        self.label_67.setText(_translate("BarStock", "Tabasco Sauce"))
        self.label_68.setText(_translate("BarStock", "Milk"))
        self.label_69.setText(_translate("BarStock", "Cream"))
        self.label_70.setText(_translate("BarStock", "Cola"))
        self.label_71.setText(_translate("BarStock", "7 Up"))
        self.label_72.setText(_translate("BarStock", "Hot Chocolate"))
        self.label_73.setText(_translate("BarStock", "Juice, Cranberry"))
        self.label_74.setText(_translate("BarStock", "Club Soda"))
        self.label_75.setText(_translate("BarStock", "Coffee"))
        self.label_76.setText(_translate("BarStock", "Juice, Lemon"))
        self.label_77.setText(_translate("BarStock", "Grenadine"))
        self.label_78.setText(_translate("BarStock", "Juice, Grapefruit"))
        self.label_79.setText(_translate("BarStock", "Juice, Apple"))
        self.label_80.setText(_translate("BarStock", "Energy Drink"))
        self.label_81.setText(_translate("BarStock", "Juice, Pineapple"))
        self.label_82.setText(_translate("BarStock", "Ice Cream"))
        self.label_83.setText(_translate("BarStock", "Half & Half"))
        self.label_84.setText(_translate("BarStock", "Ginger Ale"))
        self.label_85.setText(_translate("BarStock", "Juice, Orange"))
        self.label_86.setText(_translate("BarStock", "Juice, Peach"))
        self.label_87.setText(_translate("BarStock", "Eggnog"))
        self.label_88.setText(_translate("BarStock", "Juice, Lime"))
        self.label_89.setText(_translate("BarStock", "Tonic"))
        self.label_90.setText(_translate("BarStock", "Worcestershire"))
        self.barstock.setTabText(self.barstock.indexOf(self.mixers_tab), _translate("BarStock", "            Mixers            "))

