# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drink_list.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DrinkList(object):
    def setupUi(self, DrinkList):
        DrinkList.setObjectName("DrinkList")
        DrinkList.resize(761, 345)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DrinkList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(DrinkList)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 148, 325))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drink_menu = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.drink_menu.setObjectName("drink_menu")
        self.verticalLayout_2.addWidget(self.drink_menu)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_pgup = QtWidgets.QPushButton(DrinkList)
        self.btn_pgup.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pgup.setFont(font)
        self.btn_pgup.setObjectName("btn_pgup")
        self.verticalLayout.addWidget(self.btn_pgup)
        self.btn_up = QtWidgets.QPushButton(DrinkList)
        self.btn_up.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.btn_up.setFont(font)
        self.btn_up.setObjectName("btn_up")
        self.verticalLayout.addWidget(self.btn_up)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_down = QtWidgets.QPushButton(DrinkList)
        self.btn_down.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.btn_down.setFont(font)
        self.btn_down.setObjectName("btn_down")
        self.verticalLayout.addWidget(self.btn_down)
        self.btn_pgdown = QtWidgets.QPushButton(DrinkList)
        self.btn_pgdown.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pgdown.setFont(font)
        self.btn_pgdown.setObjectName("btn_pgdown")
        self.verticalLayout.addWidget(self.btn_pgdown)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.box_drinklbl = QtWidgets.QGroupBox(DrinkList)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.box_drinklbl.setFont(font)
        self.box_drinklbl.setObjectName("box_drinklbl")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.box_drinklbl)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_ingredients = QtWidgets.QLabel(self.box_drinklbl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ingredients.sizePolicy().hasHeightForWidth())
        self.lbl_ingredients.setSizePolicy(sizePolicy)
        self.lbl_ingredients.setMinimumSize(QtCore.QSize(94, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_ingredients.setFont(font)
        self.lbl_ingredients.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_ingredients.setObjectName("lbl_ingredients")
        self.horizontalLayout_3.addWidget(self.lbl_ingredients)
        self.lbl_image = QtWidgets.QLabel(self.box_drinklbl)
        self.lbl_image.setMinimumSize(QtCore.QSize(270, 209))
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.horizontalLayout_3.addWidget(self.lbl_image)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lbl_instructions = QtWidgets.QLabel(self.box_drinklbl)
        self.lbl_instructions.setMinimumSize(QtCore.QSize(0, 65))
        self.lbl_instructions.setMaximumSize(QtCore.QSize(377, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_instructions.setFont(font)
        self.lbl_instructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_instructions.setWordWrap(True)
        self.lbl_instructions.setObjectName("lbl_instructions")
        self.verticalLayout_4.addWidget(self.lbl_instructions)
        self.horizontalLayout.addWidget(self.box_drinklbl)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_pour = QtWidgets.QPushButton(DrinkList)
        self.btn_pour.setMinimumSize(QtCore.QSize(104, 104))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_pour.setFont(font)
        self.btn_pour.setObjectName("btn_pour")
        self.verticalLayout_3.addWidget(self.btn_pour)
        self.btn_manual = QtWidgets.QPushButton(DrinkList)
        self.btn_manual.setMinimumSize(QtCore.QSize(104, 104))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_manual.setFont(font)
        self.btn_manual.setObjectName("btn_manual")
        self.verticalLayout_3.addWidget(self.btn_manual)
        self.btn_back = QtWidgets.QPushButton(DrinkList)
        self.btn_back.setMinimumSize(QtCore.QSize(104, 104))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout_3.addWidget(self.btn_back)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(DrinkList)
        QtCore.QMetaObject.connectSlotsByName(DrinkList)

    def retranslateUi(self, DrinkList):
        _translate = QtCore.QCoreApplication.translate
        DrinkList.setWindowTitle(_translate("DrinkList", "Drink List"))
        self.btn_pgup.setText(_translate("DrinkList", "Page Up"))
        self.btn_up.setText(_translate("DrinkList", "↑"))
        self.btn_down.setText(_translate("DrinkList", "↓"))
        self.btn_pgdown.setText(_translate("DrinkList", "Page Down"))
        self.box_drinklbl.setTitle(_translate("DrinkList", "Current Drink"))
        self.lbl_ingredients.setText(_translate("DrinkList", "Ingredients:"))
        self.lbl_image.setText(_translate("DrinkList", "Image"))
        self.lbl_instructions.setText(_translate("DrinkList", "Instructions:"))
        self.btn_pour.setText(_translate("DrinkList", "Pour\n"
"Drink"))
        self.btn_manual.setText(_translate("DrinkList", "Manual\n"
"Control"))
        self.btn_back.setText(_translate("DrinkList", "Back"))

