# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manual_pour.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManualPour(object):
    def setupUi(self, ManualPour):
        ManualPour.setObjectName("ManualPour")
        ManualPour.resize(775, 378)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(ManualPour)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.p1_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_box.sizePolicy().hasHeightForWidth())
        self.p1_box.setSizePolicy(sizePolicy)
        self.p1_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p1_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p1_box.setFont(font)
        self.p1_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_box.setObjectName("p1_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.p1_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.p1_box)
        self.pushButton_7.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_7.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.p1_dec_down = QtWidgets.QPushButton(self.p1_box)
        self.p1_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p1_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p1_dec_down.setFont(font)
        self.p1_dec_down.setObjectName("p1_dec_down")
        self.horizontalLayout_8.addWidget(self.p1_dec_down)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        self.p1_val_sbox = QtWidgets.QDoubleSpinBox(self.p1_box)
        self.p1_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p1_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p1_val_sbox.setFont(font)
        self.p1_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p1_val_sbox.setReadOnly(True)
        self.p1_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p1_val_sbox.setDecimals(1)
        self.p1_val_sbox.setObjectName("p1_val_sbox")
        self.horizontalLayout_2.addWidget(self.p1_val_sbox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.p1_dec_up = QtWidgets.QPushButton(self.p1_box)
        self.p1_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p1_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p1_dec_up.setFont(font)
        self.p1_dec_up.setObjectName("p1_dec_up")
        self.horizontalLayout_9.addWidget(self.p1_dec_up)
        self.pushButton_10 = QtWidgets.QPushButton(self.p1_box)
        self.pushButton_10.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_10.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout.addWidget(self.p1_box, 1, 0, 1, 1)
        self.p2_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2_box.sizePolicy().hasHeightForWidth())
        self.p2_box.setSizePolicy(sizePolicy)
        self.p2_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p2_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p2_box.setFont(font)
        self.p2_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_box.setObjectName("p2_box")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.p2_box)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_27 = QtWidgets.QPushButton(self.p2_box)
        self.pushButton_27.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_27.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_12.addWidget(self.pushButton_27)
        self.p2_dec_down = QtWidgets.QPushButton(self.p2_box)
        self.p2_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p2_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p2_dec_down.setFont(font)
        self.p2_dec_down.setObjectName("p2_dec_down")
        self.horizontalLayout_12.addWidget(self.p2_dec_down)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.p2_val_sbox = QtWidgets.QDoubleSpinBox(self.p2_box)
        self.p2_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p2_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p2_val_sbox.setFont(font)
        self.p2_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p2_val_sbox.setReadOnly(True)
        self.p2_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p2_val_sbox.setDecimals(1)
        self.p2_val_sbox.setObjectName("p2_val_sbox")
        self.horizontalLayout_11.addWidget(self.p2_val_sbox)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.p2_dec_up = QtWidgets.QPushButton(self.p2_box)
        self.p2_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p2_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p2_dec_up.setFont(font)
        self.p2_dec_up.setObjectName("p2_dec_up")
        self.horizontalLayout_13.addWidget(self.p2_dec_up)
        self.pushButton_30 = QtWidgets.QPushButton(self.p2_box)
        self.pushButton_30.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_30.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName("pushButton_30")
        self.horizontalLayout_13.addWidget(self.pushButton_30)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_13)
        self.gridLayout.addWidget(self.p2_box, 1, 1, 1, 1)
        self.p3_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3_box.sizePolicy().hasHeightForWidth())
        self.p3_box.setSizePolicy(sizePolicy)
        self.p3_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p3_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p3_box.setFont(font)
        self.p3_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_box.setObjectName("p3_box")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.p3_box)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_31 = QtWidgets.QPushButton(self.p3_box)
        self.pushButton_31.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_31.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.horizontalLayout_15.addWidget(self.pushButton_31)
        self.p3_dec_down = QtWidgets.QPushButton(self.p3_box)
        self.p3_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p3_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p3_dec_down.setFont(font)
        self.p3_dec_down.setObjectName("p3_dec_down")
        self.horizontalLayout_15.addWidget(self.p3_dec_down)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.p3_val_sbox = QtWidgets.QDoubleSpinBox(self.p3_box)
        self.p3_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p3_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p3_val_sbox.setFont(font)
        self.p3_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p3_val_sbox.setReadOnly(True)
        self.p3_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p3_val_sbox.setDecimals(1)
        self.p3_val_sbox.setObjectName("p3_val_sbox")
        self.horizontalLayout_14.addWidget(self.p3_val_sbox)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.p3_dec_up = QtWidgets.QPushButton(self.p3_box)
        self.p3_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p3_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p3_dec_up.setFont(font)
        self.p3_dec_up.setObjectName("p3_dec_up")
        self.horizontalLayout_16.addWidget(self.p3_dec_up)
        self.pushButton_34 = QtWidgets.QPushButton(self.p3_box)
        self.pushButton_34.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_34.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_16.addWidget(self.pushButton_34)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.gridLayout.addWidget(self.p3_box, 1, 2, 1, 1)
        self.p5_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p5_box.sizePolicy().hasHeightForWidth())
        self.p5_box.setSizePolicy(sizePolicy)
        self.p5_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p5_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p5_box.setFont(font)
        self.p5_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p5_box.setObjectName("p5_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.p5_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_11 = QtWidgets.QPushButton(self.p5_box)
        self.pushButton_11.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_11.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_17.addWidget(self.pushButton_11)
        self.p5_dec_down = QtWidgets.QPushButton(self.p5_box)
        self.p5_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p5_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p5_dec_down.setFont(font)
        self.p5_dec_down.setObjectName("p5_dec_down")
        self.horizontalLayout_17.addWidget(self.p5_dec_down)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_17)
        self.p5_val_sbox = QtWidgets.QDoubleSpinBox(self.p5_box)
        self.p5_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p5_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p5_val_sbox.setFont(font)
        self.p5_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p5_val_sbox.setReadOnly(True)
        self.p5_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p5_val_sbox.setDecimals(1)
        self.p5_val_sbox.setObjectName("p5_val_sbox")
        self.horizontalLayout_3.addWidget(self.p5_val_sbox)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.p5_dec_up = QtWidgets.QPushButton(self.p5_box)
        self.p5_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p5_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p5_dec_up.setFont(font)
        self.p5_dec_up.setObjectName("p5_dec_up")
        self.horizontalLayout_18.addWidget(self.p5_dec_up)
        self.pushButton_14 = QtWidgets.QPushButton(self.p5_box)
        self.pushButton_14.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_14.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_18.addWidget(self.pushButton_14)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_18)
        self.gridLayout.addWidget(self.p5_box, 2, 1, 1, 1)
        self.p8_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p8_box.sizePolicy().hasHeightForWidth())
        self.p8_box.setSizePolicy(sizePolicy)
        self.p8_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p8_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p8_box.setFont(font)
        self.p8_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p8_box.setObjectName("p8_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.p8_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_15 = QtWidgets.QPushButton(self.p8_box)
        self.pushButton_15.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_15.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_19.addWidget(self.pushButton_15)
        self.p8_dec_down = QtWidgets.QPushButton(self.p8_box)
        self.p8_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p8_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p8_dec_down.setFont(font)
        self.p8_dec_down.setObjectName("p8_dec_down")
        self.horizontalLayout_19.addWidget(self.p8_dec_down)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_19)
        self.p8_val_sbox = QtWidgets.QDoubleSpinBox(self.p8_box)
        self.p8_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p8_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p8_val_sbox.setFont(font)
        self.p8_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p8_val_sbox.setReadOnly(True)
        self.p8_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p8_val_sbox.setDecimals(1)
        self.p8_val_sbox.setObjectName("p8_val_sbox")
        self.horizontalLayout_4.addWidget(self.p8_val_sbox)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.p8_dec_up = QtWidgets.QPushButton(self.p8_box)
        self.p8_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p8_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p8_dec_up.setFont(font)
        self.p8_dec_up.setObjectName("p8_dec_up")
        self.horizontalLayout_20.addWidget(self.p8_dec_up)
        self.pushButton_18 = QtWidgets.QPushButton(self.p8_box)
        self.pushButton_18.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_18.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_20.addWidget(self.pushButton_18)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_20)
        self.gridLayout.addWidget(self.p8_box, 3, 1, 1, 1)
        self.p11_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p11_box.sizePolicy().hasHeightForWidth())
        self.p11_box.setSizePolicy(sizePolicy)
        self.p11_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p11_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p11_box.setFont(font)
        self.p11_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p11_box.setObjectName("p11_box")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.p11_box)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_35 = QtWidgets.QPushButton(self.p11_box)
        self.pushButton_35.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_35.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_22.addWidget(self.pushButton_35)
        self.p11_dec_down = QtWidgets.QPushButton(self.p11_box)
        self.p11_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p11_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p11_dec_down.setFont(font)
        self.p11_dec_down.setObjectName("p11_dec_down")
        self.horizontalLayout_22.addWidget(self.p11_dec_down)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.p11_val_sbox = QtWidgets.QDoubleSpinBox(self.p11_box)
        self.p11_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p11_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p11_val_sbox.setFont(font)
        self.p11_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p11_val_sbox.setReadOnly(True)
        self.p11_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p11_val_sbox.setDecimals(1)
        self.p11_val_sbox.setObjectName("p11_val_sbox")
        self.horizontalLayout_21.addWidget(self.p11_val_sbox)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.p11_dec_up = QtWidgets.QPushButton(self.p11_box)
        self.p11_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p11_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p11_dec_up.setFont(font)
        self.p11_dec_up.setObjectName("p11_dec_up")
        self.horizontalLayout_23.addWidget(self.p11_dec_up)
        self.pushButton_38 = QtWidgets.QPushButton(self.p11_box)
        self.pushButton_38.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_38.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_23.addWidget(self.pushButton_38)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_23)
        self.gridLayout.addWidget(self.p11_box, 4, 1, 1, 1)
        self.p6_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p6_box.sizePolicy().hasHeightForWidth())
        self.p6_box.setSizePolicy(sizePolicy)
        self.p6_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p6_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p6_box.setFont(font)
        self.p6_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p6_box.setObjectName("p6_box")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.p6_box)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_39 = QtWidgets.QPushButton(self.p6_box)
        self.pushButton_39.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_39.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_25.addWidget(self.pushButton_39)
        self.p6_dec_down = QtWidgets.QPushButton(self.p6_box)
        self.p6_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p6_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p6_dec_down.setFont(font)
        self.p6_dec_down.setObjectName("p6_dec_down")
        self.horizontalLayout_25.addWidget(self.p6_dec_down)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.p6_val_sbox = QtWidgets.QDoubleSpinBox(self.p6_box)
        self.p6_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p6_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p6_val_sbox.setFont(font)
        self.p6_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p6_val_sbox.setReadOnly(True)
        self.p6_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p6_val_sbox.setDecimals(1)
        self.p6_val_sbox.setObjectName("p6_val_sbox")
        self.horizontalLayout_24.addWidget(self.p6_val_sbox)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.p6_dec_up = QtWidgets.QPushButton(self.p6_box)
        self.p6_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p6_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p6_dec_up.setFont(font)
        self.p6_dec_up.setObjectName("p6_dec_up")
        self.horizontalLayout_26.addWidget(self.p6_dec_up)
        self.pushButton_42 = QtWidgets.QPushButton(self.p6_box)
        self.pushButton_42.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_42.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_26.addWidget(self.pushButton_42)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_26)
        self.gridLayout.addWidget(self.p6_box, 2, 2, 1, 1)
        self.p9_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p9_box.sizePolicy().hasHeightForWidth())
        self.p9_box.setSizePolicy(sizePolicy)
        self.p9_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p9_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p9_box.setFont(font)
        self.p9_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p9_box.setObjectName("p9_box")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.p9_box)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_43 = QtWidgets.QPushButton(self.p9_box)
        self.pushButton_43.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_43.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_28.addWidget(self.pushButton_43)
        self.p9_dec_down = QtWidgets.QPushButton(self.p9_box)
        self.p9_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p9_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p9_dec_down.setFont(font)
        self.p9_dec_down.setObjectName("p9_dec_down")
        self.horizontalLayout_28.addWidget(self.p9_dec_down)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.p9_val_sbox = QtWidgets.QDoubleSpinBox(self.p9_box)
        self.p9_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p9_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p9_val_sbox.setFont(font)
        self.p9_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p9_val_sbox.setReadOnly(True)
        self.p9_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p9_val_sbox.setDecimals(1)
        self.p9_val_sbox.setObjectName("p9_val_sbox")
        self.horizontalLayout_27.addWidget(self.p9_val_sbox)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.p9_dec_up = QtWidgets.QPushButton(self.p9_box)
        self.p9_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p9_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p9_dec_up.setFont(font)
        self.p9_dec_up.setObjectName("p9_dec_up")
        self.horizontalLayout_29.addWidget(self.p9_dec_up)
        self.pushButton_46 = QtWidgets.QPushButton(self.p9_box)
        self.pushButton_46.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_46.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_29.addWidget(self.pushButton_46)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_29)
        self.gridLayout.addWidget(self.p9_box, 3, 2, 1, 1)
        self.p12_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p12_box.sizePolicy().hasHeightForWidth())
        self.p12_box.setSizePolicy(sizePolicy)
        self.p12_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p12_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p12_box.setFont(font)
        self.p12_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p12_box.setObjectName("p12_box")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.p12_box)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButton_47 = QtWidgets.QPushButton(self.p12_box)
        self.pushButton_47.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_47.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_31.addWidget(self.pushButton_47)
        self.p12_dec_down = QtWidgets.QPushButton(self.p12_box)
        self.p12_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p12_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p12_dec_down.setFont(font)
        self.p12_dec_down.setObjectName("p12_dec_down")
        self.horizontalLayout_31.addWidget(self.p12_dec_down)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        self.p12_val_sbox = QtWidgets.QDoubleSpinBox(self.p12_box)
        self.p12_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p12_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p12_val_sbox.setFont(font)
        self.p12_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p12_val_sbox.setReadOnly(True)
        self.p12_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p12_val_sbox.setDecimals(1)
        self.p12_val_sbox.setObjectName("p12_val_sbox")
        self.horizontalLayout_30.addWidget(self.p12_val_sbox)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.p12_dec_up = QtWidgets.QPushButton(self.p12_box)
        self.p12_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p12_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p12_dec_up.setFont(font)
        self.p12_dec_up.setObjectName("p12_dec_up")
        self.horizontalLayout_32.addWidget(self.p12_dec_up)
        self.pushButton_50 = QtWidgets.QPushButton(self.p12_box)
        self.pushButton_50.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_50.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setObjectName("pushButton_50")
        self.horizontalLayout_32.addWidget(self.pushButton_50)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_32)
        self.gridLayout.addWidget(self.p12_box, 4, 2, 1, 1)
        self.p4_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p4_box.sizePolicy().hasHeightForWidth())
        self.p4_box.setSizePolicy(sizePolicy)
        self.p4_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p4_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p4_box.setFont(font)
        self.p4_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p4_box.setObjectName("p4_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.p4_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.pushButton_19 = QtWidgets.QPushButton(self.p4_box)
        self.pushButton_19.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_19.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_33.addWidget(self.pushButton_19)
        self.p4_dec_down = QtWidgets.QPushButton(self.p4_box)
        self.p4_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p4_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p4_dec_down.setFont(font)
        self.p4_dec_down.setObjectName("p4_dec_down")
        self.horizontalLayout_33.addWidget(self.p4_dec_down)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_33)
        self.p4_val_sbox = QtWidgets.QDoubleSpinBox(self.p4_box)
        self.p4_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p4_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p4_val_sbox.setFont(font)
        self.p4_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p4_val_sbox.setReadOnly(True)
        self.p4_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p4_val_sbox.setDecimals(1)
        self.p4_val_sbox.setObjectName("p4_val_sbox")
        self.horizontalLayout_5.addWidget(self.p4_val_sbox)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.p4_dec_up = QtWidgets.QPushButton(self.p4_box)
        self.p4_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p4_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p4_dec_up.setFont(font)
        self.p4_dec_up.setObjectName("p4_dec_up")
        self.horizontalLayout_34.addWidget(self.p4_dec_up)
        self.pushButton_22 = QtWidgets.QPushButton(self.p4_box)
        self.pushButton_22.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_22.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_34.addWidget(self.pushButton_22)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_34)
        self.gridLayout.addWidget(self.p4_box, 2, 0, 1, 1)
        self.p7_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p7_box.sizePolicy().hasHeightForWidth())
        self.p7_box.setSizePolicy(sizePolicy)
        self.p7_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p7_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p7_box.setFont(font)
        self.p7_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p7_box.setObjectName("p7_box")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.p7_box)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.pushButton_23 = QtWidgets.QPushButton(self.p7_box)
        self.pushButton_23.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_23.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_35.addWidget(self.pushButton_23)
        self.p7_dec_down = QtWidgets.QPushButton(self.p7_box)
        self.p7_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p7_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p7_dec_down.setFont(font)
        self.p7_dec_down.setObjectName("p7_dec_down")
        self.horizontalLayout_35.addWidget(self.p7_dec_down)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_35)
        self.p7_val_sbox = QtWidgets.QDoubleSpinBox(self.p7_box)
        self.p7_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p7_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p7_val_sbox.setFont(font)
        self.p7_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p7_val_sbox.setReadOnly(True)
        self.p7_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p7_val_sbox.setDecimals(1)
        self.p7_val_sbox.setObjectName("p7_val_sbox")
        self.horizontalLayout_6.addWidget(self.p7_val_sbox)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.p7_dec_up = QtWidgets.QPushButton(self.p7_box)
        self.p7_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p7_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p7_dec_up.setFont(font)
        self.p7_dec_up.setObjectName("p7_dec_up")
        self.horizontalLayout_36.addWidget(self.p7_dec_up)
        self.pushButton_26 = QtWidgets.QPushButton(self.p7_box)
        self.pushButton_26.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_26.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_36.addWidget(self.pushButton_26)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_36)
        self.gridLayout.addWidget(self.p7_box, 3, 0, 1, 1)
        self.p10_box = QtWidgets.QGroupBox(ManualPour)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p10_box.sizePolicy().hasHeightForWidth())
        self.p10_box.setSizePolicy(sizePolicy)
        self.p10_box.setMinimumSize(QtCore.QSize(0, 0))
        self.p10_box.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.p10_box.setFont(font)
        self.p10_box.setAlignment(QtCore.Qt.AlignCenter)
        self.p10_box.setObjectName("p10_box")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.p10_box)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.pushButton_51 = QtWidgets.QPushButton(self.p10_box)
        self.pushButton_51.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_51.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setObjectName("pushButton_51")
        self.horizontalLayout_38.addWidget(self.pushButton_51)
        self.p10_dec_down = QtWidgets.QPushButton(self.p10_box)
        self.p10_dec_down.setMinimumSize(QtCore.QSize(30, 35))
        self.p10_dec_down.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p10_dec_down.setFont(font)
        self.p10_dec_down.setObjectName("p10_dec_down")
        self.horizontalLayout_38.addWidget(self.p10_dec_down)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        self.p10_val_sbox = QtWidgets.QDoubleSpinBox(self.p10_box)
        self.p10_val_sbox.setMinimumSize(QtCore.QSize(47, 0))
        self.p10_val_sbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.p10_val_sbox.setFont(font)
        self.p10_val_sbox.setAlignment(QtCore.Qt.AlignCenter)
        self.p10_val_sbox.setReadOnly(True)
        self.p10_val_sbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p10_val_sbox.setDecimals(1)
        self.p10_val_sbox.setObjectName("p10_val_sbox")
        self.horizontalLayout_37.addWidget(self.p10_val_sbox)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.p10_dec_up = QtWidgets.QPushButton(self.p10_box)
        self.p10_dec_up.setMinimumSize(QtCore.QSize(30, 35))
        self.p10_dec_up.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p10_dec_up.setFont(font)
        self.p10_dec_up.setObjectName("p10_dec_up")
        self.horizontalLayout_39.addWidget(self.p10_dec_up)
        self.pushButton_54 = QtWidgets.QPushButton(self.p10_box)
        self.pushButton_54.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_54.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setObjectName("pushButton_54")
        self.horizontalLayout_39.addWidget(self.pushButton_54)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_39)
        self.gridLayout.addWidget(self.p10_box, 4, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_reset = QtWidgets.QPushButton(ManualPour)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout.addWidget(self.btn_reset)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_start = QtWidgets.QPushButton(ManualPour)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 180))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(ManualPour)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 75))
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        self.horizontalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(ManualPour)
        self.pushButton_7.clicked.connect(self.p1_val_sbox.stepDown)
        self.pushButton_10.clicked.connect(self.p1_val_sbox.stepUp)
        self.pushButton_27.clicked.connect(self.p2_val_sbox.stepDown)
        self.pushButton_30.clicked.connect(self.p2_val_sbox.stepUp)
        self.pushButton_31.clicked.connect(self.p3_val_sbox.stepDown)
        self.pushButton_34.clicked.connect(self.p3_val_sbox.stepUp)
        self.pushButton_19.clicked.connect(self.p4_val_sbox.stepDown)
        self.pushButton_22.clicked.connect(self.p4_val_sbox.stepUp)
        self.pushButton_11.clicked.connect(self.p5_val_sbox.stepDown)
        self.pushButton_14.clicked.connect(self.p5_val_sbox.stepUp)
        self.pushButton_39.clicked.connect(self.p6_val_sbox.stepDown)
        self.pushButton_42.clicked.connect(self.p6_val_sbox.stepUp)
        self.pushButton_23.clicked.connect(self.p7_val_sbox.stepDown)
        self.pushButton_26.clicked.connect(self.p7_val_sbox.stepUp)
        self.pushButton_15.clicked.connect(self.p8_val_sbox.stepDown)
        self.pushButton_18.clicked.connect(self.p8_val_sbox.stepUp)
        self.pushButton_43.clicked.connect(self.p9_val_sbox.stepDown)
        self.pushButton_46.clicked.connect(self.p9_val_sbox.stepUp)
        self.pushButton_51.clicked.connect(self.p10_val_sbox.stepDown)
        self.pushButton_54.clicked.connect(self.p10_val_sbox.stepUp)
        self.pushButton_35.clicked.connect(self.p11_val_sbox.stepDown)
        self.pushButton_38.clicked.connect(self.p11_val_sbox.stepUp)
        self.pushButton_47.clicked.connect(self.p12_val_sbox.stepDown)
        self.pushButton_50.clicked.connect(self.p12_val_sbox.stepUp)
        QtCore.QMetaObject.connectSlotsByName(ManualPour)

    def retranslateUi(self, ManualPour):
        _translate = QtCore.QCoreApplication.translate
        ManualPour.setWindowTitle(_translate("ManualPour", "Manual Pouring"))
        self.p1_box.setTitle(_translate("ManualPour", "Pump 1"))
        self.pushButton_7.setText(_translate("ManualPour", "↞"))
        self.p1_dec_down.setText(_translate("ManualPour", "←"))
        self.p1_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_10.setText(_translate("ManualPour", "↠"))
        self.p2_box.setTitle(_translate("ManualPour", "Pump 2"))
        self.pushButton_27.setText(_translate("ManualPour", "↞"))
        self.p2_dec_down.setText(_translate("ManualPour", "←"))
        self.p2_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_30.setText(_translate("ManualPour", "↠"))
        self.p3_box.setTitle(_translate("ManualPour", "Pump 3"))
        self.pushButton_31.setText(_translate("ManualPour", "↞"))
        self.p3_dec_down.setText(_translate("ManualPour", "←"))
        self.p3_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_34.setText(_translate("ManualPour", "↠"))
        self.p5_box.setTitle(_translate("ManualPour", "Pump 5"))
        self.pushButton_11.setText(_translate("ManualPour", "↞"))
        self.p5_dec_down.setText(_translate("ManualPour", "←"))
        self.p5_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_14.setText(_translate("ManualPour", "↠"))
        self.p8_box.setTitle(_translate("ManualPour", "Pump 8"))
        self.pushButton_15.setText(_translate("ManualPour", "↞"))
        self.p8_dec_down.setText(_translate("ManualPour", "←"))
        self.p8_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_18.setText(_translate("ManualPour", "↠"))
        self.p11_box.setTitle(_translate("ManualPour", "Pump 11"))
        self.pushButton_35.setText(_translate("ManualPour", "↞"))
        self.p11_dec_down.setText(_translate("ManualPour", "←"))
        self.p11_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_38.setText(_translate("ManualPour", "↠"))
        self.p6_box.setTitle(_translate("ManualPour", "Pump 6"))
        self.pushButton_39.setText(_translate("ManualPour", "↞"))
        self.p6_dec_down.setText(_translate("ManualPour", "←"))
        self.p6_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_42.setText(_translate("ManualPour", "↠"))
        self.p9_box.setTitle(_translate("ManualPour", "Pump 9"))
        self.pushButton_43.setText(_translate("ManualPour", "↞"))
        self.p9_dec_down.setText(_translate("ManualPour", "←"))
        self.p9_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_46.setText(_translate("ManualPour", "↠"))
        self.p12_box.setTitle(_translate("ManualPour", "Pump 12"))
        self.pushButton_47.setText(_translate("ManualPour", "↞"))
        self.p12_dec_down.setText(_translate("ManualPour", "←"))
        self.p12_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_50.setText(_translate("ManualPour", "↠"))
        self.p4_box.setTitle(_translate("ManualPour", "Pump 4"))
        self.pushButton_19.setText(_translate("ManualPour", "↞"))
        self.p4_dec_down.setText(_translate("ManualPour", "←"))
        self.p4_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_22.setText(_translate("ManualPour", "↠"))
        self.p7_box.setTitle(_translate("ManualPour", "Pump 7"))
        self.pushButton_23.setText(_translate("ManualPour", "↞"))
        self.p7_dec_down.setText(_translate("ManualPour", "←"))
        self.p7_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_26.setText(_translate("ManualPour", "↠"))
        self.p10_box.setTitle(_translate("ManualPour", "Pump 10"))
        self.pushButton_51.setText(_translate("ManualPour", "↞"))
        self.p10_dec_down.setText(_translate("ManualPour", "←"))
        self.p10_dec_up.setText(_translate("ManualPour", "→"))
        self.pushButton_54.setText(_translate("ManualPour", "↠"))
        self.btn_reset.setText(_translate("ManualPour", "Reset"))
        self.btn_start.setText(_translate("ManualPour", "Start"))
        self.btn_back.setText(_translate("ManualPour", "Back"))

