# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pouring.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PourWindow(object):
    def setupUi(self, PourWindow):
        PourWindow.setObjectName("PourWindow")
        PourWindow.resize(766, 392)
        font = QtGui.QFont()
        font.setPointSize(11)
        PourWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icons/Bronx.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PourWindow.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PourWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dsp_name = QtWidgets.QLabel(PourWindow)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.dsp_name.setFont(font)
        self.dsp_name.setAlignment(QtCore.Qt.AlignCenter)
        self.dsp_name.setObjectName("dsp_name")
        self.verticalLayout.addWidget(self.dsp_name)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(PourWindow)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(PourWindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setSingleStep(0.5)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_more = QtWidgets.QPushButton(PourWindow)
        self.btn_more.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_more.setFont(font)
        self.btn_more.setObjectName("btn_more")
        self.horizontalLayout_2.addWidget(self.btn_more)
        self.btn_less = QtWidgets.QPushButton(PourWindow)
        self.btn_less.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_less.setFont(font)
        self.btn_less.setObjectName("btn_less")
        self.horizontalLayout_2.addWidget(self.btn_less)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(PourWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 523, 113))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dsp_instructions = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsp_instructions.sizePolicy().hasHeightForWidth())
        self.dsp_instructions.setSizePolicy(sizePolicy)
        self.dsp_instructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dsp_instructions.setWordWrap(True)
        self.dsp_instructions.setObjectName("dsp_instructions")
        self.verticalLayout_3.addWidget(self.dsp_instructions)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(PourWindow)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(175, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 173, 114))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dsp_ingredients = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.dsp_ingredients.setText("")
        self.dsp_ingredients.setObjectName("dsp_ingredients")
        self.verticalLayout_5.addWidget(self.dsp_ingredients)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_pour = QtWidgets.QPushButton(PourWindow)
        self.btn_pour.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.btn_pour.setFont(font)
        self.btn_pour.setAutoFillBackground(False)
        self.btn_pour.setObjectName("btn_pour")
        self.horizontalLayout_3.addWidget(self.btn_pour)
        self.btn_stop = QtWidgets.QPushButton(PourWindow)
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.btn_stop.setFont(font)
        self.btn_stop.setAutoFillBackground(False)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_3.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(PourWindow)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PourWindow)
        self.btn_more.clicked.connect(self.doubleSpinBox.stepUp)
        self.btn_less.clicked.connect(self.doubleSpinBox.stepDown)
        QtCore.QMetaObject.connectSlotsByName(PourWindow)

    def retranslateUi(self, PourWindow):
        _translate = QtCore.QCoreApplication.translate
        PourWindow.setWindowTitle(_translate("PourWindow", "Prep..."))
        self.dsp_name.setText(_translate("PourWindow", "Display drink name here."))
        self.label_3.setText(_translate("PourWindow", "Serving size:"))
        self.btn_more.setText(_translate("PourWindow", "More"))
        self.btn_less.setText(_translate("PourWindow", "Less"))
        self.groupBox.setTitle(_translate("PourWindow", "Instructions"))
        self.dsp_instructions.setText(_translate("PourWindow", "Display ingredients and instructions here."))
        self.groupBox_2.setTitle(_translate("PourWindow", "Ingredients"))
        self.btn_pour.setText(_translate("PourWindow", "Pour"))
        self.btn_stop.setText(_translate("PourWindow", "Stop"))
        self.btn_back.setText(_translate("PourWindow", "Back"))

