# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump_set_ui.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PumpSettings(object):
    def setupUi(self, PumpSettings):
        PumpSettings.setObjectName("PumpSettings")
        PumpSettings.resize(766, 391)
        PumpSettings.setMaximumSize(QtCore.QSize(800, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icons/Bronx.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PumpSettings.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PumpSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(PumpSettings)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_pump8 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump8.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump8.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump8.setFont(font)
        self.btn_pump8.setCheckable(True)
        self.btn_pump8.setObjectName("btn_pump8")
        self.gridLayout_2.addWidget(self.btn_pump8, 3, 1, 1, 1)
        self.btn_pump2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump2.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump2.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump2.setFont(font)
        self.btn_pump2.setCheckable(True)
        self.btn_pump2.setObjectName("btn_pump2")
        self.gridLayout_2.addWidget(self.btn_pump2, 0, 1, 1, 1)
        self.btn_pump7 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump7.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump7.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump7.setFont(font)
        self.btn_pump7.setCheckable(True)
        self.btn_pump7.setObjectName("btn_pump7")
        self.gridLayout_2.addWidget(self.btn_pump7, 3, 0, 1, 1)
        self.btn_pump1 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump1.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump1.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump1.setFont(font)
        self.btn_pump1.setCheckable(True)
        self.btn_pump1.setChecked(False)
        self.btn_pump1.setObjectName("btn_pump1")
        self.gridLayout_2.addWidget(self.btn_pump1, 0, 0, 1, 1)
        self.btn_pump3 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump3.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump3.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump3.setFont(font)
        self.btn_pump3.setCheckable(True)
        self.btn_pump3.setObjectName("btn_pump3")
        self.gridLayout_2.addWidget(self.btn_pump3, 0, 2, 1, 1)
        self.btn_pump4 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump4.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump4.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump4.setFont(font)
        self.btn_pump4.setCheckable(True)
        self.btn_pump4.setObjectName("btn_pump4")
        self.gridLayout_2.addWidget(self.btn_pump4, 1, 0, 1, 1)
        self.btn_pump5 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump5.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump5.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump5.setFont(font)
        self.btn_pump5.setCheckable(True)
        self.btn_pump5.setObjectName("btn_pump5")
        self.gridLayout_2.addWidget(self.btn_pump5, 1, 1, 1, 1)
        self.btn_pump6 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump6.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump6.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump6.setFont(font)
        self.btn_pump6.setCheckable(True)
        self.btn_pump6.setObjectName("btn_pump6")
        self.gridLayout_2.addWidget(self.btn_pump6, 1, 2, 1, 1)
        self.btn_pump9 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump9.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump9.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump9.setFont(font)
        self.btn_pump9.setCheckable(True)
        self.btn_pump9.setObjectName("btn_pump9")
        self.gridLayout_2.addWidget(self.btn_pump9, 3, 2, 1, 1)
        self.btn_pump10 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump10.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump10.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump10.setFont(font)
        self.btn_pump10.setCheckable(True)
        self.btn_pump10.setObjectName("btn_pump10")
        self.gridLayout_2.addWidget(self.btn_pump10, 4, 0, 1, 1)
        self.btn_pump11 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump11.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump11.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump11.setFont(font)
        self.btn_pump11.setCheckable(True)
        self.btn_pump11.setObjectName("btn_pump11")
        self.gridLayout_2.addWidget(self.btn_pump11, 4, 1, 1, 1)
        self.btn_pump12 = QtWidgets.QPushButton(self.groupBox)
        self.btn_pump12.setMinimumSize(QtCore.QSize(60, 60))
        self.btn_pump12.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_pump12.setFont(font)
        self.btn_pump12.setCheckable(True)
        self.btn_pump12.setObjectName("btn_pump12")
        self.gridLayout_2.addWidget(self.btn_pump12, 4, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(PumpSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dsp_curr_pump = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.dsp_curr_pump.setFont(font)
        self.dsp_curr_pump.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.dsp_curr_pump.setObjectName("dsp_curr_pump")
        self.verticalLayout_2.addWidget(self.dsp_curr_pump)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dsp_brand = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_brand.setFont(font)
        self.dsp_brand.setObjectName("dsp_brand")
        self.gridLayout.addWidget(self.dsp_brand, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.dsp_flavor = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_flavor.setFont(font)
        self.dsp_flavor.setObjectName("dsp_flavor")
        self.gridLayout.addWidget(self.dsp_flavor, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dsp_bottle = QtWidgets.QLineEdit(self.frame)
        self.dsp_bottle.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_bottle.setFont(font)
        self.dsp_bottle.setObjectName("dsp_bottle")
        self.horizontalLayout_3.addWidget(self.dsp_bottle)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dsp_ozleft = QtWidgets.QLineEdit(self.frame)
        self.dsp_ozleft.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_ozleft.setFont(font)
        self.dsp_ozleft.setObjectName("dsp_ozleft")
        self.horizontalLayout_3.addWidget(self.dsp_ozleft)
        self.label_8 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.dsp_oznotify = QtWidgets.QLineEdit(self.frame)
        self.dsp_oznotify.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_oznotify.setFont(font)
        self.dsp_oznotify.setText("")
        self.dsp_oznotify.setObjectName("dsp_oznotify")
        self.horizontalLayout_3.addWidget(self.dsp_oznotify)
        self.label_9 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dsp_timing = QtWidgets.QLineEdit(self.frame)
        self.dsp_timing.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_timing.setFont(font)
        self.dsp_timing.setObjectName("dsp_timing")
        self.horizontalLayout_4.addWidget(self.dsp_timing)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.dsp_speed = QtWidgets.QLineEdit(self.frame)
        self.dsp_speed.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_speed.setFont(font)
        self.dsp_speed.setObjectName("dsp_speed")
        self.horizontalLayout_4.addWidget(self.dsp_speed)
        self.chk_reverse = QtWidgets.QCheckBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chk_reverse.setFont(font)
        self.chk_reverse.setChecked(False)
        self.chk_reverse.setObjectName("chk_reverse")
        self.horizontalLayout_4.addWidget(self.chk_reverse)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.dsp_booze = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsp_booze.setFont(font)
        self.dsp_booze.setObjectName("dsp_booze")
        self.gridLayout.addWidget(self.dsp_booze, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.btn_calibrate = QtWidgets.QPushButton(self.frame)
        self.btn_calibrate.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_calibrate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_calibrate.setFont(font)
        self.btn_calibrate.setObjectName("btn_calibrate")
        self.verticalLayout_2.addWidget(self.btn_calibrate)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_prime = QtWidgets.QPushButton(self.frame_2)
        self.btn_prime.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_prime.setFont(font)
        self.btn_prime.setObjectName("btn_prime")
        self.horizontalLayout_2.addWidget(self.btn_prime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_back = QtWidgets.QPushButton(self.frame_2)
        self.btn_back.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PumpSettings)
        QtCore.QMetaObject.connectSlotsByName(PumpSettings)

    def retranslateUi(self, PumpSettings):
        _translate = QtCore.QCoreApplication.translate
        PumpSettings.setWindowTitle(_translate("PumpSettings", "Pump Settings"))
        self.groupBox.setTitle(_translate("PumpSettings", "Select Pump"))
        self.btn_pump8.setText(_translate("PumpSettings", "8"))
        self.btn_pump2.setText(_translate("PumpSettings", "2"))
        self.btn_pump7.setText(_translate("PumpSettings", "7"))
        self.btn_pump1.setText(_translate("PumpSettings", "1"))
        self.btn_pump3.setText(_translate("PumpSettings", "3"))
        self.btn_pump4.setText(_translate("PumpSettings", "4"))
        self.btn_pump5.setText(_translate("PumpSettings", "5"))
        self.btn_pump6.setText(_translate("PumpSettings", "6"))
        self.btn_pump9.setText(_translate("PumpSettings", "9"))
        self.btn_pump10.setText(_translate("PumpSettings", "10"))
        self.btn_pump11.setText(_translate("PumpSettings", "11"))
        self.btn_pump12.setText(_translate("PumpSettings", "12"))
        self.dsp_curr_pump.setText(_translate("PumpSettings", "Current Pump"))
        self.label_2.setText(_translate("PumpSettings", "Brand"))
        self.label.setText(_translate("PumpSettings", "Liquor"))
        self.label_4.setText(_translate("PumpSettings", "Bottle Size"))
        self.label_3.setText(_translate("PumpSettings", "Ounce Timing"))
        self.label_6.setText(_translate("PumpSettings", "Varient/Flavor"))
        self.label_5.setText(_translate("PumpSettings", "   Ounces Left"))
        self.label_8.setText(_translate("PumpSettings", "   Notification at"))
        self.label_9.setText(_translate("PumpSettings", "oz"))
        self.label_7.setText(_translate("PumpSettings", "Pump Speed (0-255)"))
        self.dsp_speed.setText(_translate("PumpSettings", "255"))
        self.chk_reverse.setText(_translate("PumpSettings", "Reverse Pump"))
        self.btn_calibrate.setText(_translate("PumpSettings", "Calibrate 1 Ounce"))
        self.btn_save.setText(_translate("PumpSettings", "Save"))
        self.btn_prime.setText(_translate("PumpSettings", "Prime/Test Pump"))
        self.btn_back.setText(_translate("PumpSettings", "Back"))

